# -*- coding: utf-8 -*-
"""AIML Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhsNsne0TRH-V2vCK4xVzt5UwHm-gMhX

##### City Water Consumption #####
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
data = pd.read_csv("/content/cleaned_global_water_consumption.csv")

# Print the first few rows of the dataset
print(data.head())
print(data.tail())

# Calculate the mean, median, and mode of water consumption quantity
mean_quantity = data['Total Water Consumption (Billion Cubic Meters)'].mean()
median_quantity = data['Total Water Consumption (Billion Cubic Meters)'].median()
mode_quantity = data['Total Water Consumption (Billion Cubic Meters)'].mode()
std_dev_quantity = data['Total Water Consumption (Billion Cubic Meters)'].std()

# Print the statistics
print(f'Mean Water Consumption Quantity: {mean_quantity}')
print(f'Median Water Consumption Quantity: {median_quantity}')
print(f'Mode Water Consumption Quantity: {mode_quantity}')
print(f'Standard Deviation of Water Consumption Quantity: {std_dev_quantity}')

# Plot a histogram of water consumption quantity
plt.figure(figsize=(10,6))
plt.hist(data['Total Water Consumption (Billion Cubic Meters)'], bins=10, alpha=0.5)

# Plot a scatter plot of water consumption quantity over date
plt.figure(figsize=(10,6))
plt.scatter(data['Year'], data['Total Water Consumption (Billion Cubic Meters)'], marker='o')